package www.wyq.entity;

public class Billinginfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column billinginfo.BillingId
     *
     * @mbg.generated
     */
    private Integer billingid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column billinginfo.InvoiceId
     *
     * @mbg.generated
     */
    private Integer invoiceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column billinginfo.BillingAddress
     *
     * @mbg.generated
     */
    private String billingaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column billinginfo.BillingCity
     *
     * @mbg.generated
     */
    private String billingcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column billinginfo.BillingState
     *
     * @mbg.generated
     */
    private String billingstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column billinginfo.BillingCountry
     *
     * @mbg.generated
     */
    private String billingcountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column billinginfo.BillingPostalCode
     *
     * @mbg.generated
     */
    private String billingpostalcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column billinginfo.BillingId
     *
     * @return the value of billinginfo.BillingId
     *
     * @mbg.generated
     */
    public Integer getBillingid() {
        return billingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column billinginfo.BillingId
     *
     * @param billingid the value for billinginfo.BillingId
     *
     * @mbg.generated
     */
    public void setBillingid(Integer billingid) {
        this.billingid = billingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column billinginfo.InvoiceId
     *
     * @return the value of billinginfo.InvoiceId
     *
     * @mbg.generated
     */
    public Integer getInvoiceid() {
        return invoiceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column billinginfo.InvoiceId
     *
     * @param invoiceid the value for billinginfo.InvoiceId
     *
     * @mbg.generated
     */
    public void setInvoiceid(Integer invoiceid) {
        this.invoiceid = invoiceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column billinginfo.BillingAddress
     *
     * @return the value of billinginfo.BillingAddress
     *
     * @mbg.generated
     */
    public String getBillingaddress() {
        return billingaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column billinginfo.BillingAddress
     *
     * @param billingaddress the value for billinginfo.BillingAddress
     *
     * @mbg.generated
     */
    public void setBillingaddress(String billingaddress) {
        this.billingaddress = billingaddress == null ? null : billingaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column billinginfo.BillingCity
     *
     * @return the value of billinginfo.BillingCity
     *
     * @mbg.generated
     */
    public String getBillingcity() {
        return billingcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column billinginfo.BillingCity
     *
     * @param billingcity the value for billinginfo.BillingCity
     *
     * @mbg.generated
     */
    public void setBillingcity(String billingcity) {
        this.billingcity = billingcity == null ? null : billingcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column billinginfo.BillingState
     *
     * @return the value of billinginfo.BillingState
     *
     * @mbg.generated
     */
    public String getBillingstate() {
        return billingstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column billinginfo.BillingState
     *
     * @param billingstate the value for billinginfo.BillingState
     *
     * @mbg.generated
     */
    public void setBillingstate(String billingstate) {
        this.billingstate = billingstate == null ? null : billingstate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column billinginfo.BillingCountry
     *
     * @return the value of billinginfo.BillingCountry
     *
     * @mbg.generated
     */
    public String getBillingcountry() {
        return billingcountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column billinginfo.BillingCountry
     *
     * @param billingcountry the value for billinginfo.BillingCountry
     *
     * @mbg.generated
     */
    public void setBillingcountry(String billingcountry) {
        this.billingcountry = billingcountry == null ? null : billingcountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column billinginfo.BillingPostalCode
     *
     * @return the value of billinginfo.BillingPostalCode
     *
     * @mbg.generated
     */
    public String getBillingpostalcode() {
        return billingpostalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column billinginfo.BillingPostalCode
     *
     * @param billingpostalcode the value for billinginfo.BillingPostalCode
     *
     * @mbg.generated
     */
    public void setBillingpostalcode(String billingpostalcode) {
        this.billingpostalcode = billingpostalcode == null ? null : billingpostalcode.trim();
    }
}