package www.wyq.entity;

import java.util.Date;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carId
     *
     * @mbg.generated
     */
    private String carid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.routeId
     *
     * @mbg.generated
     */
    private String routeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carType
     *
     * @mbg.generated
     */
    private String cartype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carOrgin
     *
     * @mbg.generated
     */
    private String carorgin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carProDate
     *
     * @mbg.generated
     */
    private Date carprodate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carBuyDate
     *
     * @mbg.generated
     */
    private Date carbuydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carCapacity
     *
     * @mbg.generated
     */
    private Integer carcapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.carState
     *
     * @mbg.generated
     */
    private Boolean carstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carId
     *
     * @return the value of car.carId
     *
     * @mbg.generated
     */
    public String getCarid() {
        return carid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carId
     *
     * @param carid the value for car.carId
     *
     * @mbg.generated
     */
    public void setCarid(String carid) {
        this.carid = carid == null ? null : carid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.routeId
     *
     * @return the value of car.routeId
     *
     * @mbg.generated
     */
    public String getRouteid() {
        return routeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.routeId
     *
     * @param routeid the value for car.routeId
     *
     * @mbg.generated
     */
    public void setRouteid(String routeid) {
        this.routeid = routeid == null ? null : routeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carType
     *
     * @return the value of car.carType
     *
     * @mbg.generated
     */
    public String getCartype() {
        return cartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carType
     *
     * @param cartype the value for car.carType
     *
     * @mbg.generated
     */
    public void setCartype(String cartype) {
        this.cartype = cartype == null ? null : cartype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carOrgin
     *
     * @return the value of car.carOrgin
     *
     * @mbg.generated
     */
    public String getCarorgin() {
        return carorgin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carOrgin
     *
     * @param carorgin the value for car.carOrgin
     *
     * @mbg.generated
     */
    public void setCarorgin(String carorgin) {
        this.carorgin = carorgin == null ? null : carorgin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carProDate
     *
     * @return the value of car.carProDate
     *
     * @mbg.generated
     */
    public Date getCarprodate() {
        return carprodate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carProDate
     *
     * @param carprodate the value for car.carProDate
     *
     * @mbg.generated
     */
    public void setCarprodate(Date carprodate) {
        this.carprodate = carprodate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carBuyDate
     *
     * @return the value of car.carBuyDate
     *
     * @mbg.generated
     */
    public Date getCarbuydate() {
        return carbuydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carBuyDate
     *
     * @param carbuydate the value for car.carBuyDate
     *
     * @mbg.generated
     */
    public void setCarbuydate(Date carbuydate) {
        this.carbuydate = carbuydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carCapacity
     *
     * @return the value of car.carCapacity
     *
     * @mbg.generated
     */
    public Integer getCarcapacity() {
        return carcapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carCapacity
     *
     * @param carcapacity the value for car.carCapacity
     *
     * @mbg.generated
     */
    public void setCarcapacity(Integer carcapacity) {
        this.carcapacity = carcapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.carState
     *
     * @return the value of car.carState
     *
     * @mbg.generated
     */
    public Boolean getCarstate() {
        return carstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.carState
     *
     * @param carstate the value for car.carState
     *
     * @mbg.generated
     */
    public void setCarstate(Boolean carstate) {
        this.carstate = carstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.Comment
     *
     * @return the value of car.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.Comment
     *
     * @param comment the value for car.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}