package www.wyq.entity;

import java.util.Date;

public class Deliveryreceipt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.deliveryReceiptId
     *
     * @mbg.generated
     */
    private String deliveryreceiptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.startCity
     *
     * @mbg.generated
     */
    private String startcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.endCity
     *
     * @mbg.generated
     */
    private String endcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.midCity
     *
     * @mbg.generated
     */
    private String midcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.makeDate
     *
     * @mbg.generated
     */
    private Date makedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.State
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryreceipt.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.deliveryReceiptId
     *
     * @return the value of deliveryreceipt.deliveryReceiptId
     *
     * @mbg.generated
     */
    public String getDeliveryreceiptid() {
        return deliveryreceiptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.deliveryReceiptId
     *
     * @param deliveryreceiptid the value for deliveryreceipt.deliveryReceiptId
     *
     * @mbg.generated
     */
    public void setDeliveryreceiptid(String deliveryreceiptid) {
        this.deliveryreceiptid = deliveryreceiptid == null ? null : deliveryreceiptid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.startCity
     *
     * @return the value of deliveryreceipt.startCity
     *
     * @mbg.generated
     */
    public String getStartcity() {
        return startcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.startCity
     *
     * @param startcity the value for deliveryreceipt.startCity
     *
     * @mbg.generated
     */
    public void setStartcity(String startcity) {
        this.startcity = startcity == null ? null : startcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.endCity
     *
     * @return the value of deliveryreceipt.endCity
     *
     * @mbg.generated
     */
    public String getEndcity() {
        return endcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.endCity
     *
     * @param endcity the value for deliveryreceipt.endCity
     *
     * @mbg.generated
     */
    public void setEndcity(String endcity) {
        this.endcity = endcity == null ? null : endcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.midCity
     *
     * @return the value of deliveryreceipt.midCity
     *
     * @mbg.generated
     */
    public String getMidcity() {
        return midcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.midCity
     *
     * @param midcity the value for deliveryreceipt.midCity
     *
     * @mbg.generated
     */
    public void setMidcity(String midcity) {
        this.midcity = midcity == null ? null : midcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.makeDate
     *
     * @return the value of deliveryreceipt.makeDate
     *
     * @mbg.generated
     */
    public Date getMakedate() {
        return makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.makeDate
     *
     * @param makedate the value for deliveryreceipt.makeDate
     *
     * @mbg.generated
     */
    public void setMakedate(Date makedate) {
        this.makedate = makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.State
     *
     * @return the value of deliveryreceipt.State
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.State
     *
     * @param state the value for deliveryreceipt.State
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryreceipt.Comment
     *
     * @return the value of deliveryreceipt.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryreceipt.Comment
     *
     * @param comment the value for deliveryreceipt.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}