package www.wyq.entity;

public class Deliveryplace {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.dePId
     *
     * @mbg.generated
     */
    private String depid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.mgId
     *
     * @mbg.generated
     */
    private String mgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.dePName
     *
     * @mbg.generated
     */
    private String depname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.provinceName
     *
     * @mbg.generated
     */
    private String provincename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.cityName
     *
     * @mbg.generated
     */
    private String cityname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.mgName
     *
     * @mbg.generated
     */
    private String mgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.dePTel
     *
     * @mbg.generated
     */
    private String deptel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.dePAddr
     *
     * @mbg.generated
     */
    private String depaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryplace.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.dePId
     *
     * @return the value of deliveryplace.dePId
     *
     * @mbg.generated
     */
    public String getDepid() {
        return depid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.dePId
     *
     * @param depid the value for deliveryplace.dePId
     *
     * @mbg.generated
     */
    public void setDepid(String depid) {
        this.depid = depid == null ? null : depid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.mgId
     *
     * @return the value of deliveryplace.mgId
     *
     * @mbg.generated
     */
    public String getMgid() {
        return mgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.mgId
     *
     * @param mgid the value for deliveryplace.mgId
     *
     * @mbg.generated
     */
    public void setMgid(String mgid) {
        this.mgid = mgid == null ? null : mgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.dePName
     *
     * @return the value of deliveryplace.dePName
     *
     * @mbg.generated
     */
    public String getDepname() {
        return depname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.dePName
     *
     * @param depname the value for deliveryplace.dePName
     *
     * @mbg.generated
     */
    public void setDepname(String depname) {
        this.depname = depname == null ? null : depname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.provinceName
     *
     * @return the value of deliveryplace.provinceName
     *
     * @mbg.generated
     */
    public String getProvincename() {
        return provincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.provinceName
     *
     * @param provincename the value for deliveryplace.provinceName
     *
     * @mbg.generated
     */
    public void setProvincename(String provincename) {
        this.provincename = provincename == null ? null : provincename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.cityName
     *
     * @return the value of deliveryplace.cityName
     *
     * @mbg.generated
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.cityName
     *
     * @param cityname the value for deliveryplace.cityName
     *
     * @mbg.generated
     */
    public void setCityname(String cityname) {
        this.cityname = cityname == null ? null : cityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.mgName
     *
     * @return the value of deliveryplace.mgName
     *
     * @mbg.generated
     */
    public String getMgname() {
        return mgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.mgName
     *
     * @param mgname the value for deliveryplace.mgName
     *
     * @mbg.generated
     */
    public void setMgname(String mgname) {
        this.mgname = mgname == null ? null : mgname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.dePTel
     *
     * @return the value of deliveryplace.dePTel
     *
     * @mbg.generated
     */
    public String getDeptel() {
        return deptel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.dePTel
     *
     * @param deptel the value for deliveryplace.dePTel
     *
     * @mbg.generated
     */
    public void setDeptel(String deptel) {
        this.deptel = deptel == null ? null : deptel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.dePAddr
     *
     * @return the value of deliveryplace.dePAddr
     *
     * @mbg.generated
     */
    public String getDepaddr() {
        return depaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.dePAddr
     *
     * @param depaddr the value for deliveryplace.dePAddr
     *
     * @mbg.generated
     */
    public void setDepaddr(String depaddr) {
        this.depaddr = depaddr == null ? null : depaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryplace.Comment
     *
     * @return the value of deliveryplace.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryplace.Comment
     *
     * @param comment the value for deliveryplace.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}