package www.wyq.entity;

import java.math.BigDecimal;

public class Deliveryrange {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryrange.rangeId
     *
     * @mbg.generated
     */
    private String rangeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryrange.dePId
     *
     * @mbg.generated
     */
    private String depid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryrange.areaId
     *
     * @mbg.generated
     */
    private String areaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryrange.rangeName
     *
     * @mbg.generated
     */
    private String rangename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryrange.deliveryPrice
     *
     * @mbg.generated
     */
    private BigDecimal deliveryprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column deliveryrange.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryrange.rangeId
     *
     * @return the value of deliveryrange.rangeId
     *
     * @mbg.generated
     */
    public String getRangeid() {
        return rangeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryrange.rangeId
     *
     * @param rangeid the value for deliveryrange.rangeId
     *
     * @mbg.generated
     */
    public void setRangeid(String rangeid) {
        this.rangeid = rangeid == null ? null : rangeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryrange.dePId
     *
     * @return the value of deliveryrange.dePId
     *
     * @mbg.generated
     */
    public String getDepid() {
        return depid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryrange.dePId
     *
     * @param depid the value for deliveryrange.dePId
     *
     * @mbg.generated
     */
    public void setDepid(String depid) {
        this.depid = depid == null ? null : depid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryrange.areaId
     *
     * @return the value of deliveryrange.areaId
     *
     * @mbg.generated
     */
    public String getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryrange.areaId
     *
     * @param areaid the value for deliveryrange.areaId
     *
     * @mbg.generated
     */
    public void setAreaid(String areaid) {
        this.areaid = areaid == null ? null : areaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryrange.rangeName
     *
     * @return the value of deliveryrange.rangeName
     *
     * @mbg.generated
     */
    public String getRangename() {
        return rangename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryrange.rangeName
     *
     * @param rangename the value for deliveryrange.rangeName
     *
     * @mbg.generated
     */
    public void setRangename(String rangename) {
        this.rangename = rangename == null ? null : rangename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryrange.deliveryPrice
     *
     * @return the value of deliveryrange.deliveryPrice
     *
     * @mbg.generated
     */
    public BigDecimal getDeliveryprice() {
        return deliveryprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryrange.deliveryPrice
     *
     * @param deliveryprice the value for deliveryrange.deliveryPrice
     *
     * @mbg.generated
     */
    public void setDeliveryprice(BigDecimal deliveryprice) {
        this.deliveryprice = deliveryprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column deliveryrange.Comment
     *
     * @return the value of deliveryrange.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column deliveryrange.Comment
     *
     * @param comment the value for deliveryrange.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}