package www.wyq.entity;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.mgId
     *
     * @mbg.generated
     */
    private String mgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.roleId
     *
     * @mbg.generated
     */
    private String roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.managerName
     *
     * @mbg.generated
     */
    private String managername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.managerPsd
     *
     * @mbg.generated
     */
    private String managerpsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.managerSex
     *
     * @mbg.generated
     */
    private String managersex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.Tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.Address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manager.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.mgId
     *
     * @return the value of manager.mgId
     *
     * @mbg.generated
     */
    public String getMgid() {
        return mgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.mgId
     *
     * @param mgid the value for manager.mgId
     *
     * @mbg.generated
     */
    public void setMgid(String mgid) {
        this.mgid = mgid == null ? null : mgid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.roleId
     *
     * @return the value of manager.roleId
     *
     * @mbg.generated
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.roleId
     *
     * @param roleid the value for manager.roleId
     *
     * @mbg.generated
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.managerName
     *
     * @return the value of manager.managerName
     *
     * @mbg.generated
     */
    public String getManagername() {
        return managername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.managerName
     *
     * @param managername the value for manager.managerName
     *
     * @mbg.generated
     */
    public void setManagername(String managername) {
        this.managername = managername == null ? null : managername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.managerPsd
     *
     * @return the value of manager.managerPsd
     *
     * @mbg.generated
     */
    public String getManagerpsd() {
        return managerpsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.managerPsd
     *
     * @param managerpsd the value for manager.managerPsd
     *
     * @mbg.generated
     */
    public void setManagerpsd(String managerpsd) {
        this.managerpsd = managerpsd == null ? null : managerpsd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.managerSex
     *
     * @return the value of manager.managerSex
     *
     * @mbg.generated
     */
    public String getManagersex() {
        return managersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.managerSex
     *
     * @param managersex the value for manager.managerSex
     *
     * @mbg.generated
     */
    public void setManagersex(String managersex) {
        this.managersex = managersex == null ? null : managersex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.Tel
     *
     * @return the value of manager.Tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.Tel
     *
     * @param tel the value for manager.Tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.Address
     *
     * @return the value of manager.Address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.Address
     *
     * @param address the value for manager.Address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manager.Comment
     *
     * @return the value of manager.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manager.Comment
     *
     * @param comment the value for manager.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}