package www.wyq.entity;

import java.math.BigDecimal;

public class Route {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.routeId
     *
     * @mbg.generated
     */
    private String routeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.cityId
     *
     * @mbg.generated
     */
    private String cityid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.provinceId
     *
     * @mbg.generated
     */
    private String provinceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.routeName
     *
     * @mbg.generated
     */
    private String routename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.startProvince
     *
     * @mbg.generated
     */
    private String startprovince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.startCity
     *
     * @mbg.generated
     */
    private String startcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.endProvince
     *
     * @mbg.generated
     */
    private String endprovince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.endCity
     *
     * @mbg.generated
     */
    private String endcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.midProvince
     *
     * @mbg.generated
     */
    private String midprovince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.midCity
     *
     * @mbg.generated
     */
    private String midcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.transportPrice
     *
     * @mbg.generated
     */
    private BigDecimal transportprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column route.Comment
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.routeId
     *
     * @return the value of route.routeId
     *
     * @mbg.generated
     */
    public String getRouteid() {
        return routeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.routeId
     *
     * @param routeid the value for route.routeId
     *
     * @mbg.generated
     */
    public void setRouteid(String routeid) {
        this.routeid = routeid == null ? null : routeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.cityId
     *
     * @return the value of route.cityId
     *
     * @mbg.generated
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.cityId
     *
     * @param cityid the value for route.cityId
     *
     * @mbg.generated
     */
    public void setCityid(String cityid) {
        this.cityid = cityid == null ? null : cityid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.provinceId
     *
     * @return the value of route.provinceId
     *
     * @mbg.generated
     */
    public String getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.provinceId
     *
     * @param provinceid the value for route.provinceId
     *
     * @mbg.generated
     */
    public void setProvinceid(String provinceid) {
        this.provinceid = provinceid == null ? null : provinceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.routeName
     *
     * @return the value of route.routeName
     *
     * @mbg.generated
     */
    public String getRoutename() {
        return routename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.routeName
     *
     * @param routename the value for route.routeName
     *
     * @mbg.generated
     */
    public void setRoutename(String routename) {
        this.routename = routename == null ? null : routename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.startProvince
     *
     * @return the value of route.startProvince
     *
     * @mbg.generated
     */
    public String getStartprovince() {
        return startprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.startProvince
     *
     * @param startprovince the value for route.startProvince
     *
     * @mbg.generated
     */
    public void setStartprovince(String startprovince) {
        this.startprovince = startprovince == null ? null : startprovince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.startCity
     *
     * @return the value of route.startCity
     *
     * @mbg.generated
     */
    public String getStartcity() {
        return startcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.startCity
     *
     * @param startcity the value for route.startCity
     *
     * @mbg.generated
     */
    public void setStartcity(String startcity) {
        this.startcity = startcity == null ? null : startcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.endProvince
     *
     * @return the value of route.endProvince
     *
     * @mbg.generated
     */
    public String getEndprovince() {
        return endprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.endProvince
     *
     * @param endprovince the value for route.endProvince
     *
     * @mbg.generated
     */
    public void setEndprovince(String endprovince) {
        this.endprovince = endprovince == null ? null : endprovince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.endCity
     *
     * @return the value of route.endCity
     *
     * @mbg.generated
     */
    public String getEndcity() {
        return endcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.endCity
     *
     * @param endcity the value for route.endCity
     *
     * @mbg.generated
     */
    public void setEndcity(String endcity) {
        this.endcity = endcity == null ? null : endcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.midProvince
     *
     * @return the value of route.midProvince
     *
     * @mbg.generated
     */
    public String getMidprovince() {
        return midprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.midProvince
     *
     * @param midprovince the value for route.midProvince
     *
     * @mbg.generated
     */
    public void setMidprovince(String midprovince) {
        this.midprovince = midprovince == null ? null : midprovince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.midCity
     *
     * @return the value of route.midCity
     *
     * @mbg.generated
     */
    public String getMidcity() {
        return midcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.midCity
     *
     * @param midcity the value for route.midCity
     *
     * @mbg.generated
     */
    public void setMidcity(String midcity) {
        this.midcity = midcity == null ? null : midcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.transportPrice
     *
     * @return the value of route.transportPrice
     *
     * @mbg.generated
     */
    public BigDecimal getTransportprice() {
        return transportprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.transportPrice
     *
     * @param transportprice the value for route.transportPrice
     *
     * @mbg.generated
     */
    public void setTransportprice(BigDecimal transportprice) {
        this.transportprice = transportprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column route.Comment
     *
     * @return the value of route.Comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column route.Comment
     *
     * @param comment the value for route.Comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}