package www.wyq.dao;

import java.util.List;
import www.wyq.entity.Billinginfo;

public interface BillinginfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billinginfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer billingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billinginfo
     *
     * @mbg.generated
     */
    int insert(Billinginfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billinginfo
     *
     * @mbg.generated
     */
    Billinginfo selectByPrimaryKey(Integer billingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billinginfo
     *
     * @mbg.generated
     */
    List<Billinginfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table billinginfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Billinginfo record);
}