package www.wyq.dao;

import java.util.List;
import www.wyq.entity.Deliveryreceipt;

public interface DeliveryreceiptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryreceipt
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String deliveryreceiptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryreceipt
     *
     * @mbg.generated
     */
    int insert(Deliveryreceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryreceipt
     *
     * @mbg.generated
     */
    Deliveryreceipt selectByPrimaryKey(String deliveryreceiptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryreceipt
     *
     * @mbg.generated
     */
    List<Deliveryreceipt> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryreceipt
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Deliveryreceipt record);
}