package www.wyq.dao;

import java.util.List;
import www.wyq.entity.Deliveryrange;

public interface DeliveryrangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryrange
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String rangeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryrange
     *
     * @mbg.generated
     */
    int insert(Deliveryrange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryrange
     *
     * @mbg.generated
     */
    Deliveryrange selectByPrimaryKey(String rangeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryrange
     *
     * @mbg.generated
     */
    List<Deliveryrange> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deliveryrange
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Deliveryrange record);
}