package www.wyq.dao;

import java.util.List;
import www.wyq.entity.Order1;

public interface Order1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order1
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order1
     *
     * @mbg.generated
     */
    int insert(Order1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order1
     *
     * @mbg.generated
     */
    Order1 selectByPrimaryKey(String orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order1
     *
     * @mbg.generated
     */
    List<Order1> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order1
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Order1 record);
}